export const VILLES_CI = [
  "Abengourou", "Abidjan", "Abobo", "Abobo-Baoulé", "Abobo-Doumé",
  "Aboisso", "Adiaké", "Adjamé", "Adzopé", "Affery", "Agboville",
  "Agou", "Akoupé", "Alépé", "Anoumaba", "Arrah", "Assinie",
  "Attecoube", "Attécoubé", "Ayamé", "Azaguié", "Bangolo", "Béoumi",
  "Biankouma", "Bingerville", "Bloléquin", "Bocanda", "Bondoukou",
  "Bongouanou", "Bonon", "Bonoua", "Booko", "Borotou", "Botro",
  "Bouaflé", "Bouaké", "Brofodoumé", "Boundiali", "Bouna", "Buyo",
  "Cocody", "Cocody-Angré", "Cocody-II-Plateaux", "Cocody-Riviera",
  "Dabakala", "Dabou", "Daloa", "Danané", "Daoukro", "Diabo",
  "Dianra", "Dianra-Village", "Diéouzon", "Dikodougou", "Dimbokro",
  "Divo", "Doropo", "Duékoué", "Facobly", "Ferkessédougou", "Fresco",
  "Gagnoa", "Grand-Bassam", "Grand-Béréby", "Grand-Lahou", "Guéyo",
  "Guiglo", "Guitry", "Hiré", "Issia", "Jacqueville", "Kani",
  "Kaniasso", "Kanzra", "Katiola", "Kong", "Koro", "Kouibly",
  "Koumassi", "Koumassi-Remblais", "Koun-Fao", "Kouto", "Lakota",
  "Logoualé", "Madinani", "Maféré", "Mahapleu", "Man", "Mankono",
  "Marcory", "Marcory-Biétry", "Marcory-Zone4", "Méagui", "Minignan",
  "Morondo", "M'Bahiakro", "M'Batto", "Nassian", "Niablé",
  "Niakaramadougou", "Nielle", "Niofoin", "Odienné", "Ouangolodougou",
  "Ouaninou", "Ouellé", "Oumé", "Ouragahio", "Plateau", "Port-Bouët",
  "Port-Bouët-Vridi", "Sakassou", "Samatiguila", "San-Pédro",
  "Sangouiné", "Sarhala", "Sassandra", "Séguéla", "Sérébou",
  "Sikensi", "Sinfra", "Sipilou", "Songon", "Soubré", "Taabo",
  "Tabou", "Tafiré", "Taï", "Tanda", "Tehini", "Tengrela",
  "Tiapoum", "Tiassalé", "Tiébissou", "Tieningboué", "Tortiya",
  "Touba", "Toumodi", "Transua", "Treichville", "Treichville-Arras",
  "Vavoua", "Yakassé-Attobrou", "Yamoussoukro", "Yopougon",
  "Yopougon-Kouté", "Yopougon-Sicogi", "Zikisso", "Zouan-Hounien",
  "Zoukougbeu", "Zuénoula"
]